# Generated by Django 5.2.6 on 2025-11-24 15:03

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelInstruccionEspecifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_instruccion', models.CharField(max_length=100, unique=True)),
                ('descripcion_instruccion', models.TextField(blank=True)),
                ('activa_instruccion', models.BooleanField(default=True)),
                ('fecha_instruccion', models.DateField(auto_now_add=True, verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'Instrucción Especifica',
                'verbose_name_plural': 'Instrucciones Especificas',
                'db_table': 'instruccionespecifica',
            },
        ),
        migrations.CreateModel(
            name='ModelControlTramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ini_control', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('fecha_fin_control', models.DateField(blank=True, null=True, verbose_name='Fecha Fin Control')),
                ('codigo_control', models.CharField(max_length=50, unique=True, verbose_name='Código de Control')),
                ('asunto_control', models.CharField(max_length=255, verbose_name='Asunto del Trámite')),
                ('tipo_control', models.CharField(blank=True, choices=[('NOTA', 'Nota'), ('INFORME', 'Informe'), ('COMUNICADO_INTERNO', 'Comunicado Interno')], max_length=100, null=True, verbose_name='Tipo Documento')),
                ('estado_control', models.BooleanField(blank=True, default=False, null=True, verbose_name='Estado Activo/Inactivo')),
                ('origen_control', models.CharField(choices=[('GERENCIA_GENERAL', 'Gerencia General'), ('ASESORIA_LEGAL', 'Asesoría Legal'), ('CLUB_GENTE_GRANDE', 'Club Gente Grande'), ('AMBITO_REGULATORIO', 'Ámbito Regulatorio'), ('TECNOLOGIAS_DE_LA_INFORMACION', 'Tecnologías de la Información'), ('GERENCIA_COMERCIAL', 'Gerencia Comercial'), ('GERENCIA_COMERCIAL_CORPORATIVA', 'Gerencia Comercial Corporativa'), ('EQUIPO_VENTAS_EMPRESAS', 'Equipo Ventas Empresas'), ('EQUIPO_DESARROLLO_MARKETING_COMUNICACION', 'Equipo Desarrollo de Marketing y Comunicación'), ('EQUIPO_TRABAJO_TERRITORIO_SUD', 'Equipo de Trabajo Territorio Sud'), ('EQUIPO_TRABAJO_TERRITORIO_QUILLACOLLO', 'Equipo de Trabajo Territorio Quillacollo'), ('EQUIPO_TRABAJO_TERRITORIO_NORTE', 'Equipo de Trabajo Territorio Norte'), ('EQUIPO_TRABAJO_TERRITORIO_HIPODROMO', 'Equipo de Trabajo Territorio Hipódromo'), ('EQUIPO_TRABAJO_TERRITORIO_CENTRO', 'Equipo de Trabajo Territorio Centro'), ('EQUIPO_CENTRO_DE_LLAMADAS', 'Equipo Centro de Llamadas'), ('EQUIPO_ATENCION_RETENCION_SOCIO', 'Equipo Atención y Retención al Socio'), ('EQUIPO_ATENCION_RETENCION_CLIENTE', 'Equipo Atención y Retención al Cliente'), ('DIVISION_RELACION_EXPERIENCIA_CLIENTE', 'División Relación y Experiencia del Cliente'), ('DIVISION_GESTION_INTEGRAL_TERRITORIOS', 'División Gestión Integral de Territorios'), ('DIVISION_GESTION_DE_LA_OFERTA', 'División Gestión de la Oferta'), ('GERENCIA_ADMINISTRACION_FINANZAS', 'Gerencia de Administración y Finanzas'), ('DEPARTAMENTO_CONTABILIDAD', 'Departamento Contabilidad'), ('DIVISION_FACTURACION_COBRANZAS', 'División Facturación y Cobranzas'), ('DIVISION_FINANZAS', 'División Finanzas'), ('UNIDAD_ATENCION_RECLAMOS_FACTURA', 'Unidad de Trabajo Atención Reclamos Factura'), ('UNIDAD_TRABAJO_CARTERA', 'Unidad de Trabajo Cartera'), ('UNIDAD_TRABAJO_COBRANZAS', 'Unidad de Trabajo Cobranzas'), ('UNIDAD_TRABAJO_PROCESOS', 'Unidad de Trabajo Procesos'), ('DEPARTAMENTO_ACTIVOS_FIJOS', 'Departamento Activos Fijos'), ('DEPARTAMENTO_EXTENSION_SOCIAL_COOPERATIVA', 'Departamento Extensión Social Cooperativa'), ('DIVISION_ADMINISTRACION_SERVICIOS', 'División Administración y Servicios'), ('DIVISION_GESTION_DE_RECURSOS_HUMANOS', 'División Gestión de Recursos Humanos'), ('GERENCIA_ADMINISTRACION_ABASTECIMIENTO', 'Gerencia de Administración de Abastecimiento'), ('UNIDAD_TRABAJO_ALMACENES', 'Unidad de Trabajo Almacenes'), ('UNIDAD_TRABAJO_ARCHIVOS', 'Unidad de Trabajo Archivos'), ('UNIDAD_TRABAJO_SEGURIDAD_FISICA_INDUSTRIAL', 'Unidad de Trabajo Seguridad Física e Industrial'), ('UNIDAD_TRABAJO_SEGURO_DELEGADO', 'Unidad de Trabajo Seguro Delegado'), ('UNIDAD_TRABAJO_SERVICIOS_GENERALES_LOGISTICA', 'Unidad de Trabajo Servicios Generales y Logística'), ('UNIDAD_TRABAJO_TALLERES', 'Unidad de Trabajo Talleres'), ('GERENCIA_PRODUCCION', 'Gerencia Produccion'), ('CENTRO_OPERACIONES_CENTRO_CONDEBAMBA', 'Centro de Operaciones Centro Condebamba'), ('CENTRO_OPERACIONES_HIPODROMO', 'Centro de Operaciones Hipódromo'), ('CENTRO_OPERACIONES_NORTE_SACABA', 'Centro de Operaciones Norte Sacaba'), ('CENTRO_OPERACIONES_QUILLACOLLO', 'Centro de Operaciones Quillacollo'), ('CENTRO_OPERACIONES_SUD_VALLE', 'Centro de Operaciones Sud Valle'), ('DEPARTAMENTO_DWDM', 'Departamento DWDM'), ('DEPARTAMENTO_ENERGIA_FUERZA', 'Departamento Energía y Fuerza'), ('DEPARTAMENTO_INTERNET', 'Departamento Internet'), ('DEPARTAMENTO_PLATAFORMAS_TRANSMISION_TERRESTRE', 'Departamento Plataformas de Transmisión Terrestre'), ('DEPARTAMENTO_TELEVISION', 'Departamento Televisión'), ('DEPARTAMENTO_TRANSPORTE_INALAMBRICO', 'Departamento Transporte Inalámbrico'), ('DEPARTAMENTO_VOZ', 'Departamento Voz'), ('DIVISION_GESTION_DE_RECURSOS_PRODUCCION', 'División Gestión de Recursos'), ('DIVISION_GESTION_DEL_SERVICIO', 'División Gestión del Servicio'), ('HELP_DESK', 'Help Desk'), ('APLICACIONES', 'Aplicaciones'), ('GESTION_INVENTARIO_RECURSOS', 'Gestión del Inventario de Recursos'), ('MONITOREO_SERVICIOS_RECURSOS', 'Monitoreo Servicios y Recursos'), ('MANTENIMIENTO_DE_REDES', 'Mantenimiento de Redes'), ('MESA_DE_PRUEBAS', 'Mesa de Pruebas'), ('GERENCIA_PLANIFICACION', 'Gerencia de Planificación'), ('DIVISION_PLANIFICACION_DISENO_REDES', 'División Planificación y Diseño de Redes'), ('DIVISION_PLANIFICACION_CONTROL_GESTION', 'División Planificación y Control de Gestión'), ('DIVISION_GESTION_DE_CALIDAD', 'División Gestión de Calidad'), ('NOTA_EXTERNO', 'Nota Externa')], max_length=150, verbose_name='Origen del Trámite')),
                ('nota_control', models.CharField(blank=True, max_length=100, verbose_name='Nota de Control')),
                ('informe_control', models.CharField(blank=True, verbose_name='Informe de Control')),
                ('com_int_control', models.CharField(blank=True, verbose_name='ComInt')),
                ('documento_pdf', models.FileField(upload_to='documentosTramites/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Documento Adjunto (PDF)')),
                ('nombre_empleado_control', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del Empleado')),
                ('origen_ruta_control', models.CharField(blank=True, max_length=150, verbose_name='Unidad Origen')),
                ('instruccion_complementaria_control', models.TextField(blank=True, verbose_name='Instrucción Complementaria')),
                ('estado_ruta_control', models.BooleanField(blank=True, default=False, null=True, verbose_name='Estado derivación inicial')),
                ('destino_ruta_control', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='auth.group', verbose_name='Unidad Destino')),
                ('instruccion_especifica_control', models.ManyToManyField(blank=True, help_text='Selecciona una o más categorías', to='appTramite.modelinstruccionespecifica', verbose_name='Intrucción Especifica')),
            ],
            options={
                'verbose_name': 'Control de Trámite',
                'verbose_name_plural': 'Controles de Trámites',
                'db_table': 'controltramite',
            },
        ),
        migrations.CreateModel(
            name='ModelRutaTramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen_ruta', models.CharField(max_length=150, verbose_name='Origen de la Ruta')),
                ('fecha_ini_ruta', models.DateField(default=datetime.date.today, verbose_name='Fecha Inicio de Ruta')),
                ('fecha_fin_ruta', models.DateField(blank=True, null=True, verbose_name='Fecha Fin de Ruta')),
                ('estado_ruta', models.BooleanField(blank=True, default=False, null=True, verbose_name='Ruta Activa')),
                ('instruccion_especifica', models.TextField(blank=True, max_length=150, verbose_name='Instrucción Específica')),
                ('ie_para_su_atencion', models.BooleanField(blank=True, null=True, verbose_name='1. Para su Atención')),
                ('ie_para_su_conocimiento', models.BooleanField(blank=True, null=True, verbose_name='2. Para su Conocimiento')),
                ('ie_para_su_analsis', models.BooleanField(blank=True, null=True, verbose_name='3. Para su Análisis e Informe')),
                ('ie_para_su_aprobacion', models.BooleanField(blank=True, null=True, verbose_name='4. Para su Aprobación')),
                ('ie_para_su_regularizacion', models.BooleanField(blank=True, null=True, verbose_name='5. Para su Regularización')),
                ('ie_proceder_al_pago', models.BooleanField(blank=True, null=True, verbose_name='6. Proceder al Pago')),
                ('ie_para_su_archivo', models.BooleanField(blank=True, null=True, verbose_name='7. Para su Archivo')),
                ('ie_dar_cumplimiento', models.BooleanField(blank=True, null=True, verbose_name='8. Dar Cumplimiento')),
                ('ie_tratamiento_urgente', models.BooleanField(blank=True, null=True, verbose_name='9. Tratamiento Urgente')),
                ('ie_se_adjunta_nota', models.BooleanField(blank=True, null=True, verbose_name='10. Se Adjunta Nota')),
                ('ie_para_descargo', models.BooleanField(blank=True, null=True, verbose_name='11. Para Descargo')),
                ('ie_autorizado', models.BooleanField(blank=True, null=True, verbose_name='12. Autorizado')),
                ('ie_elaborar_contrato', models.BooleanField(blank=True, null=True, verbose_name='13. Elaborar Contrato')),
                ('ie_otro', models.BooleanField(blank=True, null=True, verbose_name='14. Otros')),
                ('instruccion_complementaria', models.TextField(blank=True, verbose_name='Instrucción Complementaria')),
                ('origen_nombre_empleado', models.CharField(max_length=200, verbose_name='Nombre Empleado Origen')),
                ('destino_nombre_empleado', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre Empleado Destino')),
                ('control_tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas_asociadas', to='appTramite.modelcontroltramite', verbose_name='Trámite')),
                ('destino_ruta', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='auth.group', verbose_name='Destino de la Ruta')),
                ('instruccion_especifica_ruta', models.ManyToManyField(blank=True, help_text='Selecciona una o más categorías', to='appTramite.modelinstruccionespecifica', verbose_name='Instrucción Específica')),
            ],
            options={
                'verbose_name': 'Ruta de Trámite',
                'verbose_name_plural': 'Rutas de Trámites',
                'db_table': 'rutatramite',
            },
        ),
    ]
