# Generated by Django 5.2.6 on 2025-12-22 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTramite', '0002_alter_modelcontroltramite_destino_ruta_control'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelcontroltramite',
            name='nombre_empleado_control',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Empleado Responsable'),
        ),
    ]
