# Generated by Django 5.2.6 on 2025-12-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTramite', '0003_alter_modelcontroltramite_nombre_empleado_control'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelrutatramite',
            name='fecha_resepcion_ruta',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Recepción de Ruta'),
        ),
    ]
