# Generated by Django 5.2.6 on 2025-12-23 17:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTramite', '0004_modelrutatramite_fecha_resepcion_ruta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelcontroltramite',
            name='fecha_fin_control',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Fin Control'),
        ),
        migrations.AlterField(
            model_name='modelcontroltramite',
            name='fecha_ini_control',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='modelrutatramite',
            name='fecha_fin_ruta',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Fin de Ruta'),
        ),
        migrations.AlterField(
            model_name='modelrutatramite',
            name='fecha_ini_ruta',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='Fecha Inicio de Ruta'),
        ),
    ]
