# Generated by Django 5.2.6 on 2025-12-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTramite', '0005_alter_modelcontroltramite_fecha_fin_control_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelrutatramite',
            name='fecha_ini_ruta',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha Inicio de Ruta'),
        ),
    ]
