# Generated by Django 5.2.6 on 2025-12-30 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAuth', '0003_cargomodel_usuariomodel_cargo_usuario'),
        ('appTramite', '0006_alter_modelrutatramite_fecha_ini_ruta'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelcontroltramite',
            name='anio_codigo_control',
            field=models.CharField(blank=True, max_length=4, verbose_name='Año de Trámite'),
        ),
        migrations.AddField(
            model_name='modelcontroltramite',
            name='gerencia_codigo_control',
            field=models.CharField(blank=True, max_length=150, verbose_name='Gerencia/Unidad Responsable'),
        ),
        migrations.AddField(
            model_name='modelcontroltramite',
            name='numero_secuencial_codigo_control',
            field=models.CharField(blank=True, max_length=20, verbose_name='Número Secuencial'),
        ),
        migrations.AddField(
            model_name='modelcontroltramite',
            name='unidad_destino_codigo_control',
            field=models.CharField(blank=True, choices=[('acronimo_unidad', 'nombre_unidad'), ('acronimo_unidad', 'nombre_unidad'), ('acronimo_unidad', 'nombre_unidad'), ('acronimo_unidad', 'nombre_unidad'), ('acronimo_unidad', 'nombre_unidad'), ('acronimo_unidad', 'nombre_unidad'), ('acronimo_unidad', 'nombre_unidad'), ('acronimo_unidad', 'nombre_unidad'), ('acronimo_unidad', 'nombre_unidad'), ('acronimo_unidad', 'nombre_unidad'), ('acronimo_unidad', 'nombre_unidad'), ('acronimo_unidad', 'nombre_unidad'), ('acronimo_unidad', 'nombre_unidad'), ('acronimo_unidad', 'nombre_unidad'), ('acronimo_unidad', 'nombre_unidad'), ('acronimo_unidad', 'nombre_unidad'), ('acronimo_unidad', 'nombre_unidad'), ('acronimo_unidad', 'nombre_unidad'), ('acronimo_unidad', 'nombre_unidad'), ('acronimo_unidad', 'nombre_unidad'), ('acronimo_unidad', 'nombre_unidad'), ('acronimo_unidad', 'nombre_unidad'), ('acronimo_unidad', 'nombre_unidad'), ('acronimo_unidad', 'nombre_unidad'), ('acronimo_unidad', 'nombre_unidad'), ('acronimo_unidad', 'nombre_unidad'), ('acronimo_unidad', 'nombre_unidad'), ('acronimo_unidad', 'nombre_unidad'), ('acronimo_unidad', 'nombre_unidad')], max_length=150, verbose_name='Unidad Destino'),
        ),
        migrations.AlterField(
            model_name='modelcontroltramite',
            name='destino_ruta_control',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='appAuth.unidadmodel', verbose_name='Unidad Destino'),
        ),
        migrations.AlterField(
            model_name='modelrutatramite',
            name='destino_ruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='appAuth.unidadmodel', verbose_name='Destino de la Ruta'),
        ),
    ]
