# Generated by Django 5.2.6 on 2026-01-07 19:37

import appTramite.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTramite', '0007_modelcontroltramite_anio_codigo_control_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelcontroltramite',
            name='unidad_destino_codigo_control',
            field=models.CharField(blank=True, choices=appTramite.models.get_unidad_choices, max_length=150, verbose_name='Unidad Destino'),
        ),
    ]
