# Generated by Django 5.2.6 on 2026-01-20 13:20

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTramite', '0008_alter_modelcontroltramite_unidad_destino_codigo_control'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cite', models.CharField(editable=False, max_length=50, unique=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('titulo', models.CharField(max_length=255)),
                ('contenido', ckeditor.fields.RichTextField()),
                ('tipo_documento', models.CharField(choices=[('CARTA', 'Carta'), ('NOTA', 'Nota Interna'), ('INFORME', 'Informe'), ('CIRCULAR', 'Circular'), ('MEMO', 'Memorandum')], max_length=20)),
                ('adjunto', models.FileField(blank=True, null=True, upload_to='docs/%Y/%m/')),
                ('bpm_control', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appTramite.modelcontroltramite')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='destinatario', to=settings.AUTH_USER_MODEL)),
                ('usuario_creador', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='creador', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'db_table': 'documento',
            },
        ),
    ]
