# Generated by Django 5.2.6 on 2026-01-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTramite', '0009_documentomodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentomodel',
            name='adjunto',
            field=models.FileField(blank=True, null=True, upload_to='media/CNITM/%Y/%m/'),
        ),
    ]
