# Generated by Django 5.2.6 on 2026-01-20 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appTramite', '0010_alter_documentomodel_adjunto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentomodel',
            old_name='adjunto',
            new_name='adjunto_documento',
        ),
        migrations.RenameField(
            model_name='documentomodel',
            old_name='bpm_control',
            new_name='bpm_control_documento',
        ),
        migrations.RenameField(
            model_name='documentomodel',
            old_name='cite',
            new_name='cite_documento',
        ),
        migrations.RenameField(
            model_name='documentomodel',
            old_name='contenido',
            new_name='contenido_documento',
        ),
        migrations.RenameField(
            model_name='documentomodel',
            old_name='destinatario',
            new_name='destinatario_documento',
        ),
        migrations.RenameField(
            model_name='documentomodel',
            old_name='fecha',
            new_name='fecha_documento',
        ),
        migrations.RenameField(
            model_name='documentomodel',
            old_name='titulo',
            new_name='titulo_documento',
        ),
        migrations.RenameField(
            model_name='documentomodel',
            old_name='usuario_creador',
            new_name='usuario_creador_documento',
        ),
    ]
