# Generated by Django 5.2.6 on 2026-01-26 16:03

import appTramite.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTramite', '0011_rename_adjunto_documentomodel_adjunto_documento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentomodel',
            name='anio_documento',
            field=models.CharField(blank=True, max_length=4, verbose_name='Año de Documento'),
        ),
        migrations.AddField(
            model_name='documentomodel',
            name='numero_secuencial_documento',
            field=models.CharField(blank=True, max_length=20, verbose_name='Número Secuencial'),
        ),
        migrations.AddField(
            model_name='documentomodel',
            name='unidad_documento',
            field=models.CharField(blank=True, choices=appTramite.models.get_unidad_choices, max_length=150, verbose_name='Unidad Origen'),
        ),
        migrations.AlterField(
            model_name='documentomodel',
            name='cite_documento',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='CITE del Documento'),
        ),
        migrations.AlterField(
            model_name='documentomodel',
            name='tipo_documento',
            field=models.CharField(choices=[('C', 'Carta'), ('N', 'Nota Interna'), ('INF', 'Informe'), ('CIR', 'Circular'), ('M', 'Memorandum')], max_length=20),
        ),
    ]
