# Generated by Django 5.2.6 on 2026-01-26 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAuth', '0003_cargomodel_usuariomodel_cargo_usuario'),
        ('appTramite', '0012_documentomodel_anio_documento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentomodel',
            name='destinatario_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='destinatario', to='appAuth.usuariomodel'),
        ),
    ]
