# Generated by Django 5.2.6 on 2026-02-03 13:39

import appTramite.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAuth', '0004_alter_usuariomodel_gerente_usuario'),
        ('appTramite', '0014_modelrutatramite_documento_adjunto_ruta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelcontroltramite',
            name='usuario_jerarquia_control',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='appAuth.usuariomodel', verbose_name='Usuario Jerarquico Responsable'),
        ),
        migrations.AlterField(
            model_name='modelcontroltramite',
            name='destino_ruta_control',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='appAuth.unidadmodel', verbose_name='Unidad Destino del Tramite'),
        ),
        migrations.AlterField(
            model_name='modelcontroltramite',
            name='origen_control',
            field=models.CharField(choices=[('GERENCIA GENERAL', 'Gerencia General'), ('ASESORIA LEGAL', 'Asesoría Legal'), ('CLUB GENTE GRANDE', 'Club Gente Grande'), ('AMBITO REGULATORIO', 'Ámbito Regulatorio'), ('DIVISION TECNOLOGIAS DE LA INFORMACION', 'Tecnologías de la Información'), ('GERENCIA COMERCIAL', 'Gerencia Comercial'), ('GERENCIA COMERCIAL CORPORATIVA', 'Gerencia Comercial Corporativa'), ('EQUIPO VENTAS EMPRESAS', 'Equipo Ventas Empresas'), ('EQUIPO DESARROLLO MARKETING COMUNICACION', 'Equipo Desarrollo de Marketing y Comunicación'), ('EQUIPO TRABAJO TERRITORIO SUD', 'Equipo de Trabajo Territorio Sud'), ('EQUIPO TRABAJO TERRITORIO QUILLACOLLO', 'Equipo de Trabajo Territorio Quillacollo'), ('EQUIPO TRABAJO TERRITORIO NORTE', 'Equipo de Trabajo Territorio Norte'), ('EQUIPO TRABAJO TERRITORIO HIPODROMO', 'Equipo de Trabajo Territorio Hipódromo'), ('EQUIPO TRABAJO TERRITORIO CENTRO', 'Equipo de Trabajo Territorio Centro'), ('EQUIPO CENTRO DE LLAMADAS', 'Equipo Centro de Llamadas'), ('EQUIPO ATENCION RETENCION SOCIO', 'Equipo Atención y Retención al Socio'), ('EQUIPO ATENCION RETENCION CLIENTE', 'Equipo Atención y Retención al Cliente'), ('DIVISION RELACION EXPERIENCIA CLIENTE', 'División Relación y Experiencia del Cliente'), ('DIVISION GESTION INTEGRAL TERRITORIOS', 'División Gestión Integral de Territorios'), ('DIVISION GESTION DE LA OFERTA', 'División Gestión de la Oferta'), ('GERENCIA ADMINISTRACION FINANZAS', 'Gerencia de Administración y Finanzas'), ('DEPARTAMENTO CONTABILIDAD', 'Departamento Contabilidad'), ('DIVISION FACTURACION COBRANZAS', 'División Facturación y Cobranzas'), ('DIVISION FINANZAS', 'División Finanzas'), ('UNIDAD ATENCION RECLAMOS FACTURA', 'Unidad de Trabajo Atención Reclamos Factura'), ('UNIDAD TRABAJO CARTERA', 'Unidad de Trabajo Cartera'), ('UNIDAD TRABAJO COBRANZAS', 'Unidad de Trabajo Cobranzas'), ('UNIDAD TRABAJO PROCESOS', 'Unidad de Trabajo Procesos'), ('DEPARTAMENTO ACTIVOS FIJOS', 'Departamento Activos Fijos'), ('DEPARTAMENTO EXTENSION SOCIAL COOPERATIVA', 'Departamento Extensión Social Cooperativa'), ('DIVISION ADMINISTRACION SERVICIOS', 'División Administración y Servicios'), ('DIVISION GESTION DE RECURSOS HUMANOS', 'División Gestión de Recursos Humanos'), ('GERENCIA ADMINISTRACION ABASTECIMIENTO', 'Gerencia de Administración de Abastecimiento'), ('UNIDAD TRABAJO ALMACENES', 'Unidad de Trabajo Almacenes'), ('UNIDAD TRABAJO ARCHIVOS', 'Unidad de Trabajo Archivos'), ('UNIDAD TRABAJO SEGURIDAD FISICA INDUSTRIAL', 'Unidad de Trabajo Seguridad Física e Industrial'), ('UNIDAD TRABAJO SEGURO DELEGADO', 'Unidad de Trabajo Seguro Delegado'), ('UNIDAD TRABAJO SERVICIOS GENERALES LOGISTICA', 'Unidad de Trabajo Servicios Generales y Logística'), ('UNIDAD TRABAJO TALLERES', 'Unidad de Trabajo Talleres'), ('GERENCIA PRODUCCION', 'Gerencia Produccion'), ('CENTRO OPERACIONES CENTRO CONDEBAMBA', 'Centro de Operaciones Centro Condebamba'), ('CENTRO OPERACIONES HIPODROMO', 'Centro de Operaciones Hipódromo'), ('CENTRO OPERACIONES NORTE SACABA', 'Centro de Operaciones Norte Sacaba'), ('CENTRO OPERACIONES QUILLACOLLO', 'Centro de Operaciones Quillacollo'), ('CENTRO OPERACIONES SUD VALLE', 'Centro de Operaciones Sud Valle'), ('DEPARTAMENTO DWDM', 'Departamento DWDM'), ('DEPARTAMENTO ENERGIA FUERZA', 'Departamento Energía y Fuerza'), ('DEPARTAMENTO INTERNET', 'Departamento Internet'), ('DEPARTAMENTO PLATAFORMAS TRANSMISION TERRESTRE', 'Departamento Plataformas de Transmisión Terrestre'), ('DEPARTAMENTO TELEVISION', 'Departamento Televisión'), ('DEPARTAMENTO TRANSPORTE INALAMBRICO', 'Departamento Transporte Inalámbrico'), ('DEPARTAMENTO VOZ', 'Departamento Voz'), ('DIVISION GESTION DE RECURSOS PRODUCCION', 'División Gestión de Recursos'), ('DIVISION GESTION DEL SERVICIO', 'División Gestión del Servicio'), ('HELP DESK', 'Help Desk'), ('APLICACIONES', 'Aplicaciones'), ('GESTION INVENTARIO RECURSOS', 'Gestión del Inventario de Recursos'), ('MONITOREO SERVICIOS RECURSOS', 'Monitoreo Servicios y Recursos'), ('MANTENIMIENTO DE REDES', 'Mantenimiento de Redes'), ('MESA DE PRUEBAS', 'Mesa de Pruebas'), ('GERENCIA PLANIFICACION', 'Gerencia de Planificación'), ('DIVISION PLANIFICACION DISENO REDES', 'División Planificación y Diseño de Redes'), ('DIVISION PLANIFICACION CONTROL GESTION', 'División Planificación y Control de Gestión'), ('DIVISION GESTION DE CALIDAD', 'División Gestión de Calidad'), ('NOTA_EXTERNO', 'Nota Externa')], max_length=150, verbose_name='Unidad Origen del Trámite'),
        ),
        migrations.AlterField(
            model_name='modelcontroltramite',
            name='unidad_destino_codigo_control',
            field=models.CharField(blank=True, choices=appTramite.models.get_unidad_choices, max_length=150, verbose_name='Unidad Origen del Doc.'),
        ),
    ]
