# Generated by Django 5.2.6 on 2026-02-03 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAuth', '0004_alter_usuariomodel_gerente_usuario'),
        ('appTramite', '0015_modelcontroltramite_usuario_jerarquia_control_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelcontroltramite',
            name='destino_jerarquia_control',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='tramites_jerarquia', to='appAuth.unidadmodel', verbose_name='Destino Jerarquico del Tramite'),
        ),
        migrations.AlterField(
            model_name='modelrutatramite',
            name='control_tramite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='rutas_asociadas', to='appTramite.modelcontroltramite', verbose_name='Trámite'),
        ),
    ]
