# Generated by Django 5.2.6 on 2026-02-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTramite', '0016_modelcontroltramite_destino_jerarquia_control_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelrutatramite',
            name='tipo_ruta',
            field=models.CharField(blank=True, choices=[('CONTROL', 'Control'), ('REVISION', 'Revision'), ('OTRO', 'Otro')], max_length=150, null=True, verbose_name='Tipo de Ruta'),
        ),
    ]
