# Generated by Django 5.2.6 on 2026-02-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTramite', '0017_modelrutatramite_tipo_ruta'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelcontroltramite',
            name='path_jerarquia_control',
            field=models.TextField(blank=True, verbose_name='Path de usuario_a al usuario_b'),
        ),
    ]
