# Generated by Django 5.2.6 on 2026-02-06 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAuth', '0004_alter_usuariomodel_gerente_usuario'),
        ('appTramite', '0018_modelcontroltramite_path_jerarquia_control'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelrutatramite',
            name='usuario_destino_ruta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='appAuth.usuariomodel', verbose_name='Destinatario'),
        ),
    ]
