# Generated by Django 5.2.6 on 2026-02-10 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAuth', '0004_alter_usuariomodel_gerente_usuario'),
        ('appTramite', '0019_modelrutatramite_usuario_destino_ruta'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelcontroltramite',
            name='usuario_ruta_control',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='usuario_destino', to='appAuth.usuariomodel', verbose_name='Usuario Jerarquico Responsable'),
        ),
        migrations.AlterField(
            model_name='modelcontroltramite',
            name='usuario_jerarquia_control',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='usuario_jerarquia', to='appAuth.usuariomodel', verbose_name='Usuario Jerarquico Responsable'),
        ),
    ]
