# Generated by Django 5.2.6 on 2025-11-24 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_grupo', models.CharField(max_length=150, unique=True, verbose_name='Nombre de Grupo')),
                ('detalle_grupo', models.CharField(blank=True, max_length=150, null=True, verbose_name='Detalle de Grupo')),
                ('acronimo_grupo', models.CharField(max_length=150, unique=True, verbose_name='Acronimo del Nombre de Grupo')),
                ('fecha_grupo', models.DateField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('tipo_grupo', models.CharField(blank=True, max_length=150, null=True, verbose_name='Tipo de Grupo')),
                ('ruta_grupo', models.CharField(blank=True, max_length=150, null=True, verbose_name='Ruta del Grupo')),
                ('estado_grupo', models.BooleanField(default=True, verbose_name='Estado de Grupo')),
                ('superior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='children', to='appAuth.grupomodel', verbose_name='Grupo Superior')),
                ('usuarios', models.ManyToManyField(blank=True, help_text='Seleccione una o más usuarios', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'db_table': 'grupo',
            },
        ),
        migrations.CreateModel(
            name='UsuarioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_usuario', models.CharField(max_length=150, verbose_name='Username')),
                ('password_usuario', models.CharField(max_length=150, verbose_name='Contraseña')),
                ('firstname_usuario', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre de Usuario')),
                ('lastname_usuario', models.CharField(blank=True, max_length=150, null=True, verbose_name='Apellido de Usuario')),
                ('email_usuario', models.EmailField(blank=True, max_length=150, null=True, verbose_name='Correo de Usuario')),
                ('active_usuario', models.BooleanField(default=True, verbose_name='Usuario Activo')),
                ('item_usuario', models.CharField(blank=True, max_length=150, null=True, verbose_name='Item de Usuario')),
                ('tipo_usuario', models.CharField(blank=True, max_length=150, null=True, verbose_name='Tipo de Usuario')),
                ('gerente_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='children', to='appAuth.usuariomodel', verbose_name='Gerente de Area')),
                ('grupo_usuario', models.ManyToManyField(blank=True, help_text='Seleccione una o más grupos', to='appAuth.grupomodel', verbose_name='Unidad')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
            },
        ),
    ]
