# Generated by Django 5.2.6 on 2025-11-27 13:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAuth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariomodel',
            name='grupo_usuario',
        ),
        migrations.AddField(
            model_name='usuariomodel',
            name='fecha_usuario',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha Creación'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UnidadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_unidad', models.CharField(max_length=150, unique=True, verbose_name='Nombre de Unidad')),
                ('detalle_unidad', models.CharField(blank=True, max_length=150, null=True, verbose_name='Detalle de Unidad')),
                ('acronimo_unidad', models.CharField(max_length=150, unique=True, verbose_name='Acronimo del Nombre de Unidad')),
                ('fecha_unidad', models.DateField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('tipo_unidad', models.CharField(blank=True, max_length=150, null=True, verbose_name='Tipo de Unidad')),
                ('ruta_unidad', models.CharField(blank=True, max_length=150, null=True, verbose_name='Ruta de la Unidad')),
                ('estado_unidad', models.BooleanField(default=True, verbose_name='Estado de Unidad')),
                ('superior_unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='children', to='appAuth.unidadmodel', verbose_name='Unidad Superior')),
            ],
            options={
                'verbose_name': 'Unidad',
                'verbose_name_plural': 'Unidades',
                'db_table': 'unidad',
            },
        ),
        migrations.AddField(
            model_name='usuariomodel',
            name='unidad_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='appAuth.unidadmodel', verbose_name='Unidad de Usuario'),
        ),
        migrations.DeleteModel(
            name='GrupoModel',
        ),
    ]
