# Generated by Django 5.2.6 on 2025-12-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAuth', '0002_remove_usuariomodel_grupo_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cargo', models.CharField(max_length=150, unique=True, verbose_name='Nombre de Cargo')),
                ('detalle_cargo', models.CharField(blank=True, max_length=150, null=True, verbose_name='Detalle de Cargo')),
                ('fecha_cargo', models.DateField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('estado_cargo', models.BooleanField(default=True, verbose_name='Estado de Cargo')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'db_table': 'cargo',
            },
        ),
        migrations.AddField(
            model_name='usuariomodel',
            name='cargo_usuario',
            field=models.ManyToManyField(blank=True, to='appAuth.cargomodel', verbose_name='Cargo de Usuario'),
        ),
    ]
