# Generated by Django 5.2.6 on 2026-02-03 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAuth', '0003_cargomodel_usuariomodel_cargo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariomodel',
            name='gerente_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='children', to='appAuth.usuariomodel', verbose_name='Jefe Superior'),
        ),
    ]
