# Generated by Django 5.2.6 on 2026-02-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAuth', '0004_alter_usuariomodel_gerente_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariomodel',
            name='password_dos_usuario',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Contraseña complementaria:'),
        ),
    ]
