"""
Django settings for tramites project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import ckeditor, ckeditor_uploader
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-v$#(2oxdyq1+qt2-jtyo4!5qay1+952^*7ac$7r8_@a5hujrvc'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Configuracion para desarrollo local
ALLOWED_HOSTS = ['*']
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'http://192.9.220.112:8000/',  # Tu IP local
]

# Use environment variables in Docker. Default values kept for local development.
# DEBUG = bool(os.environ.get("DEBUG", 0))
# SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', SECRET_KEY)
# ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",")
# CSRF_TRUSTED_ORIGINS = [
#     'https://sistram.comteco.com.bo',
#     'https://www.sistram.comteco.com.bo',
# ]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'appAuth',
    'appTramite',
    'ckeditor',
    'ckeditor_uploader',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tramites.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tramites.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    # If Postgres env vars are set, use Postgres, otherwise fallback to sqlite3
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    },
    # 'default': {
    #     'ENGINE': 'django.db.backends.postgresql',
    #     'NAME': 'controltramites',
    #     'USER': 'gestorip',
    #     'PASSWORD': 'gestorip',
    #     'HOST': 'localhost',
    #     'PORT': '5432',
    # }
    # "default": {
    #     "ENGINE": "django.db.backends.postgresql",
    #     "NAME": os.environ.get("POSTGRES_DB"),
    #     "USER": os.environ.get("POSTGRES_USER"),
    #     "PASSWORD": os.environ.get("POSTGRES_PASSWORD"),
    #     "HOST": os.environ.get("POSTGRES_HOST"),
    #     "PORT": os.environ.get("POSTGRES_PORT"),
    # }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-us'

TIME_ZONE = 'America/La_Paz'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# Optionally allow overriding static root via env
STATIC_ROOT = os.environ.get('STATIC_ROOT', STATIC_ROOT)

# CKEditor Settings
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'Custom',
        'toolbar_Custom': [
            {'name': 'styles', 'items': ['Styles', 'Format']},
            # {'name': 'document', 'items': ['Source', '-', 'Save', 'NewPage', 'Preview', 'Print']},
            {'name': 'size', 'items': ['FontSize']},
            {'name': 'alignment', 'items': ['JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock']},
            {'name': 'basicstyles', 'items': ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript']},
            {'name': 'clipboard', 'items': ['Cut', 'Copy', 'Paste', 'Undo', 'Redo']},
            {'name': 'paragraph', 'items': ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-',]},
            # {'name': 'links', 'items': ['Link', 'Unlink', 'Anchor']},
            {'name': 'insert', 'items': ['Image', 'Table', 'HorizontalRule', 'SpecialChar']},
            {'name': 'colors', 'items': ['TextColor', 'BGColor']},
            {'name': 'tools', 'items': ['Maximize', 'ShowBlocks']},
        ],
        'height': 400,
        'width': '100%',
    },
}



# 1. MEDIA_URL: La parte de la URL que precede a los archivos subidos.
# Ej: http://127.0.0.1:8000/media/
MEDIA_URL = '/media/'

# 2. MEDIA_ROOT: El directorio físico en el disco donde se almacenarán los archivos.
# Esto creará una carpeta 'media' en la raíz de tu proyecto.
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# o usando Path: MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# LDAP / Authentication notes
# If you plan to use LDAP authentication with `django-python3-ldap`, follow the
# package documentation to configure the LDAP backend and connection settings.
# Typical steps:
# 1. Add the LDAP authentication backend to `AUTHENTICATION_BACKENDS` (so Django
#    will try LDAP before or alongside the default ModelBackend).
# 2. Add the necessary connection settings (server URI, bind DN/credentials,
#    search base, attribute mappings). Keep secrets out of source control.
#
# Example (fill values and uncomment when ready):
#
LOGIN_REDIRECT_URL = 'index'
LOGIN_URL = 'login'
# LOGOUT_REDIRECT_URL = 'login'

# Tiempo de permanencia logueado en segundos
# SESSION_COOKIE_AGE = 3600 # 1 hora
# SESSION_EXPIRE_AT_BROWSER_CLOSE = True


AUTHENTICATION_BACKENDS = (
		'django.contrib.auth.backends.ModelBackend',
		'appAuth.conexion.Autenticacion',
	)
# AUTHENTICATION_BACKENDS = [
#     'django_python3_ldap.auth.ldapbackend.LDAPBackend',  # check package docs for exact path
#     'django.contrib.auth.backends.ModelBackend',
# ]
#
# # ldap connection settings (example placeholders)
# LDAP_AUTH_URL = "ldap://ldap.example.com"
# LDAP_AUTH_USE_TLS = True
# LDAP_AUTH_SEARCH_BASE = "ou=users,dc=example,dc=com"
# LDAP_AUTH_USER_FIELDS = {
#     "username": "uid",
#     "first_name": "givenName",
#     "last_name": "sn",
#     "email": "mail",
# }
# --------------------------------------------------------------------------
# CONFIGURACIÓN PARA PERMITIR INCRUSTACIÓN (Modal sin Iframe/Embed/Object)
# --------------------------------------------------------------------------

# Por defecto en Django 3.0+ es 'DENY' (denegar siempre) o 'SAMEORIGIN' si se usa 
# el middleware de clickjacking.
# Si el PDF se abre en pestaña nueva pero no en el modal, este es el culpable.

X_FRAME_OPTIONS = 'SAMEORIGIN'

